# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20161016_1856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('id_user',)]),
        ),
    ]
