# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20161016_1903'),
    ]
