# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='', max_length=3),
        ),
    ]
