# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
