# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 17:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBook',
            fields=[
                ('id_base_book', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=70)),
                ('author', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('cover_image', models.ImageField(default='../../media/default_images/default_cover.png', upload_to='../../media/cover_images/')),
                ('isbn', models.CharField(default='', max_length=13)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None)),
            ],
        ),
    ]
