# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_books', '0002_auto_20161018_0032'),
        ('base_books', '0005_auto_20161018_1950'),
    ]

    operations = [
    ]
