# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_books', '0006_auto_20161019_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebook',
            name='cover_image',
            field=models.ImageField(default='/home/hunter/Desktop/lendMyBookDevf/lendmybook/media/default_images/default_cover.png', upload_to='cover_images/'),
        ),
    ]
