# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 17:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_auto_20161016_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), default=[], size=None)),
                ('status', models.BooleanField(default=False)),
                ('id_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
