# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20161016_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='base_book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base_books.BaseBook'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id_book',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
