# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20161016_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='aditional_info',
            field=models.TextField(default='No info'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(default='1st', max_length=20),
        ),
    ]
