# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20161016_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_book',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
