# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_images',
            field=models.ImageField(default='/Users/manuelojeda/Documents/lendmybook/media/default_images/default_cover.png', upload_to='/Users/manuelojeda/Documents/lendmybook/media/book_images/'),
        ),
    ]
