# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20161019_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_images',
        ),
    ]
