# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_book_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id_book',
            new_name='id',
        ),
    ]
