# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20161021_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='id_book',
        ),
    ]
